apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: hacbs-iib-trigger-template
objects:
  - apiVersion: tekton.dev/v1beta1
    kind: Task
    metadata:
      name: iib-operations
    spec:
      stepTemplate:
        env:
          - name: STORAGE_DRIVER
            value: vfs
      steps:
        - name: iib-add-poc
          image: registry.access.redhat.com/ubi8/ubi
          resources:
            limits:
              memory: 2Gi
              cpu: 200m
            requests:
              memory: 2Gi
              cpu: 200m
          script: |
            curl -L https://github.com/fullstorydev/grpcurl/releases/download/v1.8.5/grpcurl_1.8.5_linux_x86_64.tar.gz -o /var/grpcurl_1.8.5_linux_x86_64.tar.gz
            cd /usr/bin && tar -xf /var/grpcurl_1.8.5_linux_x86_64.tar.gz grpcurl && rm -f /var/grpcurl_1.8.5_linux_x86_64.tar.gz
            curl -L https://github.com/operator-framework/operator-registry/releases/download/v1.23.2/linux-amd64-opm -o /var/opm
            cp /var/opm /usr/bin/opm && chmod 0555 /usr/bin/opm  && rm -f /var/opm
            yum -y install buildah podman skopeo jq
            sed -i 's/^short-name-mode = .*/short-name-mode = "disabled"/' /etc/containers/registries.conf
            echo "Simulating IIB Add Request"
            # skopeo --command-timeout 300s inspect docker://registry-proxy.engineering.redhat.com/rh-osbs/iib-pub:v4.11 --raw
            grpcurl -plaintext localhost:50051 list api.Registry 
            # grpcurl -plaintext localhost:50051 api.Registry/ListBundles
            opm registry add --database /var/iib/imageconfigs/index.db --enable-alpha --bundle-images "" --overwrite-latest
            opm migrate /var/iib/imageconfigs/index.db /tmp/iib-xnlfzy4l/catalog
            opm generate dockerfile /tmp/iib-xnlfzy4l/catalog --binary-image registry.redhat.io/openshift4/ose-operator-registry:v4.11
            cd /tmp/iib-xnlfzy4l/
            buildah bud --no-cache --format docker --override-arch amd64 --arch amd64 -t iib-build:312452-amd64 -f /tmp/iib-xnlfzy4l/catalog.Dockerfile .
            buildah bud --no-cache --format docker --override-arch arm64 --arch arm64 -t iib-build:312452-arm64 -f /tmp/iib-xnlfzy4l/catalog.Dockerfile .
            podman push -q iib-build:312452-amd64 docker://quay.io/scoheb/tekton-iib-test:312452-amd64
            podman push -q iib-build:312452-arm64 docker://quay.io/scoheb/tekton-iib-test:312452-arm64
            buildah manifest create quay.io/scoheb/tekton-iib-test:312452
            buildah manifest add quay.io/scoheb/tekton-iib-test:312452 docker://quay.io/scoheb/tekton-iib-test:312452-amd64
            buildah manifest add quay.io/scoheb/tekton-iib-test:312452 docker://quay.io/scoheb/tekton-iib-test:312452-arm64
            buildah manifest push --all --format v2s2 quay.io/scoheb/tekton-iib-test:312452 docker://quay.io/scoheb/tekton-iib-test:312452
            echo "Index Image uploaded successfully"
          securityContext:
            capabilities:
              add:
                - SETFCAP
          volumeMounts:
            - name: imageconfigs
              mountPath: /var/iib/imageconfigs
      sidecars:
        - name: grpc
          ##image: registry.redhat.io/redhat/redhat-operator-index:v4.11
          image:  registry-proxy.engineering.redhat.com/rh-osbs/iib-pub-pending:v4.12
          resources:
            limits:
              memory: 2Gi
              cpu: 200m
            requests:
              memory: 2Gi
              cpu: 200m
          script: |
            cp -r /configs /var/iib/imageconfigs
            cp -r /var/lib/iib/_hidden/do.not.edit.db /var/iib/imageconfigs/index.db
            opm serve /configs --port=50051 -t /dev/null
          volumeMounts:
            - name: imageconfigs
              mountPath: /var/iib/imageconfigs
            - mountPath: /var/lib/containers
              name: varlibcontainers
      volumes:
        - emptyDir: {}
          name: imageconfigs
        - emptyDir: {}
          name: varlibcontainers
  - apiVersion: tekton.dev/v1beta1
    kind: Pipeline
    metadata:
      name: iib-add
    spec:
      tasks:
        - name: iib-operations
          taskRef:
            name: iib-operations
